fix(GoalPreview): pin latest state comment
taskany-inc/issues pull request #1290
Opened 2023-07-10 15:47 UTC by DenisVorop

## PR includes

- [x] Feature

## Related issues

Resolve #1177 

## QA Instructions, Screenshots, Recordings
  
<img width="360" alt="Снимок экрана 2023-07-10 в 18 46 26" src="https://github.com/taskany-inc/issues/assets/95316053/a6123007-7ab4-412b-8862-8f6bceb6a727">

2023-07-12 05:04 UTC, 9teen90nine requested changes
We don't make copies!

2023-07-12 05:04 UTC, 9teen90nine commented on src/components/CommentFixed.tsx
> +                <CardComment>
this looks a lot like a copy-paste of a comment component with some logic stripped of
you need either combine them into a single one or somehow reference one from another

2023-07-13 09:12 UTC, 9teen90nine requested changes
you should create new files for support components and make them components, not render functions

2023-07-13 09:12 UTC, 9teen90nine commented on src/components/CommentView/CommentView.tsx
> +const iconRenderCondition = (isPinned: boolean, image?: User['image'], email?: User['email']) =>
this too

2023-07-14 14:21 UTC, DenisVorop reviewed
nothing

2023-07-14 16:08 UTC, closed without merging