Save criteria changes to the history
taskany-inc/issues pull request #1294
Opened 2023-07-12 20:10 UTC by LamaEats

## PR includes

- [x] Refactor
- [x] Feature

## Related issues

Resolve #1196 

## QA Instructions, Screenshots, Recordings
  
<img width="468" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/97312f97-2754-42d7-87eb-9d3bc61b3082">

2023-07-17 14:33 UTC, awinogradov requested changes

2023-07-18 09:42 UTC, LamaEats commented on src/utils/db.ts
> +    }, {} as Record<keyof HistoryRecordSubject, { ids: string[]; sourceIdx: number[] }>);
TS cannon assign type from reduce fn to empty object as initial arg

2023-07-18 10:05 UTC, LamaEats commented on src/utils/db.ts
> +        const valuesAsIds = allValues.length ? allValues.every((val) => stringIsCiudOrId(val)) : false;
#1312

2023-07-18 15:18 UTC, awinogradov reviewed
Still...
<img width="450" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/5b0efeed-b572-42ec-8701-31f2ebe52e31">

2023-07-18 19:30 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.tsx
> +                        isChangeAction={isChangeAction}
Why not to do this same as on [428](https://github.com/taskany-inc/issues/pull/1294/files#diff-28e7bb86d913c391369eee9c1f6a73620a9b73b57ac0771d78c2eff181931ac4R428) line? It's better in terms of composition.

2023-07-19 09:29 UTC, awinogradov approved these changes

2023-07-20 09:57 UTC, merged