Hide goal description diff in history under cut
taskany-inc/issues pull request #1300
Opened 2023-07-13 16:05 UTC by Troff8

## PR includes

- [ ] Feature

## Related issues

Resolve [#1238 ](https://github.com/taskany-inc/issues/issues/1238)

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/87986652/a437d57a-9728-49dc-9a0c-5a77d792af7f

https://github.com/taskany-inc/issues/assets/87986652/e2df90ab-0060-4a1c-8365-b47106b6a11b

2023-07-14 13:44 UTC, 9teen90nine requested changes

2023-07-14 13:44 UTC, 9teen90nine commented on src/components/HistoryRecord/HistoryRecord.tsx
> +    }, [viewDestiption]);
unnecessary useCallback

2023-07-16 13:32 UTC, Troff8 commented on src/components/HistoryRecord/HistoryRecord.tsx
> +    }, [viewDestiption]);
ok 💪🏻

2023-07-17 15:11 UTC, 9teen90nine approved these changes

2023-07-17 15:17 UTC, awinogradov requested changes
Do not change icon color

2023-07-18 13:00 UTC, awinogradov requested changes

2023-07-18 13:22 UTC, Troff8 commented on src/components/HistoryRecord/HistoryRecord.tsx
> +                        {action !== 'change' && (
{action:'change'} only appears when the title/description changes. For the title and description component, I added a <RelativeTime> . This was necessary in order not to add another action

2023-07-18 13:25 UTC, Troff8 commented on src/components/HistoryRecord/HistoryRecord.tsx
> +            <Text size="xs">
I added <RelativeTime> in the right place - before the button.

2023-07-18 15:13 UTC, awinogradov requested changes
<img width="569" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/013806fa-5059-454d-a2ad-1a72b461eacc">

2023-07-18 19:25 UTC, awinogradov requested changes
Still...

<img width="532" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/8f7d7223-d350-43cd-830a-2f6c67bcd629">

2023-07-19 12:49 UTC, awinogradov approved these changes

2023-07-19 12:53 UTC, merged