Issues/1326
taskany-inc/issues pull request #1362
Opened 2023-07-24 20:46 UTC by DenisVorop

## PR includes

- [x] Bug Fix

## Related issues

Resolve #1326 
Related issues #1230 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/1b96f812-9528-4715-a921-ba177824e84f

2023-07-25 09:01 UTC, 9teen90nine approved these changes

2023-07-25 09:01 UTC, 9teen90nine commented on src/components/CommentCreateForm/CommentCreateForm.tsx
>              // FIXME: maybe async/await would be better API
probably you could remove this comment

2023-07-25 09:32 UTC, awinogradov requested changes
Now

<img width="682" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/6c5858bd-7d37-4087-b35f-f0414f3b59a0">


Must be

<img width="689" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/4ace9551-78d4-47eb-a67d-cb92c1f98b2f">

2023-07-25 12:43 UTC, DenisVorop commented
https://github.com/taskany-inc/issues/assets/95316053/fafe1f0f-938a-49fd-b6ee-59b0b950a55a

2023-07-26 10:48 UTC, DenisVorop commented
https://github.com/taskany-inc/issues/assets/95316053/68e9db36-f982-413a-b4d8-b03f3a4742b5

2023-07-26 20:31 UTC, DenisVorop commented
the latest video

https://github.com/taskany-inc/issues/assets/95316053/217cab0a-df8c-452c-8f04-65467e0f986c

2023-07-26 20:38 UTC, awinogradov approved these changes

2023-07-26 20:52 UTC, merged