Goal creation success toast is always in en locale
taskany-inc/issues pull request #1403
Opened 2023-07-31 08:47 UTC by Troff8

## PR includes

- [ ] Bug Fix

## Related issues

Resolve [#1381 ](https://github.com/taskany-inc/issues/issues/1381)

2023-07-31 09:11 UTC, 9teen90nine approved these changes

2023-07-31 09:43 UTC, awinogradov requested changes
https://github.com/taskany-inc/issues/blob/main/src/components/NotificationsHub/NotificationHub.map.ts#L36

So, we are using map to create event details. It's already wrapped in `tr` function but it doesn't work because it uses `tr` out of components context.

2023-07-31 15:58 UTC, awinogradov requested changes

2023-07-31 15:58 UTC, awinogradov commented on src/components/NotificationsHub/NotificationHub.map.ts
> +export default createNotificicationKeyMap;
I'm not sure you need default export here

2023-07-31 15:58 UTC, awinogradov commented on src/utils/dispatchNotification.ts
> +            detail: createNotificicationKeyMap(key),
Can you spelling issue in the name of function?

2023-08-01 10:14 UTC, awinogradov approved these changes

2023-08-01 10:15 UTC, merged