User can edit criteria
taskany-inc/issues pull request #1410
Opened 2023-07-31 13:13 UTC by LamaEats

## PR includes

- [x] Refactor
- [x] Feature

## Related issues

Resolve #1240
Resolve #1329 

## QA Instructions, Screenshots, Recordings

<img width="710" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/b5ea3255-1ea3-49e9-a569-bb55eaec40b9">
<img width="710" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/91858999-3b0e-459b-9620-c4b975acd576">
<img width="710" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/998c9f0d-208d-42c7-81fa-0bc8732ef854">
<img width="710" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/a6e89e41-1c6b-496d-a04a-7b876088f996">
<img width="710" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/e3904217-a224-4bd4-977a-8542b62e9e66">
<img width="728" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/09032022-2eda-413f-8754-023db67bca3d">

2023-07-31 15:54 UTC, awinogradov requested changes

2023-07-31 15:54 UTC, awinogradov commented on src/components/CriteriaForm/CriteriaForm.tsx
> +            btnText={tr('Save')}
`actionButtonText` would be better. Same as in GoalForm.

2023-07-31 15:54 UTC, awinogradov commented on src/components/CriteriaForm/CriteriaForm.tsx
> +    /* more specific above base style rules */
Can we fix it in TableRow component?

2023-08-01 10:08 UTC, LamaEats commented on src/components/GoalDependencyList/GoalDependencyList.tsx
> +                                <StyledTitle size="s" weight="bold" onClick={onClickHandler} as="a">
Because native `cursor: pointer;` prop by hover on an element and shows interactive element, also the semantic correct markup

2023-08-02 14:52 UTC, awinogradov approved these changes

2023-08-03 10:00 UTC, LamaEats commented on src/components/GoalPreview/GoalPreview.tsx
> +                                        {nullable(_isEditable, () => (
Yep, 'cause the same feature

2023-08-03 10:03 UTC, LamaEats commented on trpc/router/goal.ts
> +                            id: ctx.session.user.activityId,
We're planing that to implement checker in the other issue for specific routes

2023-08-03 10:04 UTC, 9teen90nine commented on src/components/GoalPreview/GoalPreview.tsx
> +                                        {nullable(_isEditable, () => (
can't it be a component instead of a copy?

2023-08-03 10:18 UTC, LamaEats commented on src/components/GoalPreview/GoalPreview.tsx
> +                                        {nullable(_isEditable, () => (
Let's do it in the other issue :)

2023-08-03 10:19 UTC, 9teen90nine approved these changes

2023-08-03 10:20 UTC, LamaEats commented on src/components/GoalPreview/GoalPreview.tsx
> +                                        {nullable(_isEditable, () => (
https://github.com/taskany-inc/issues/issues/1430

2023-08-03 10:46 UTC, merged