Estimate form is not working
taskany-inc/issues pull request #1417
Opened 2023-08-01 16:53 UTC by DenisVorop

## PR includes

- [x] Bug Fix
- [x] Refactor

## Related issues
Resolve #1397 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/f4c1bcf9-1bee-4455-888c-fa89cb068193

2023-08-01 18:46 UTC, awinogradov requested changes

2023-08-01 18:46 UTC, awinogradov commented on src/utils/dateTime.ts
> +export const incYearIfDateHasPassed = (date: Date) => {
`dateTime.test.ts` ;)

2023-08-01 21:16 UTC, awinogradov approved these changes

2023-08-02 07:59 UTC, 9teen90nine approved these changes
We should get rid of this picker asap

2023-08-02 10:46 UTC, merged