Global search is barely visible to users
taskany-inc/issues pull request #1567
Opened 2023-08-23 11:57 UTC by awinogradov

## PR includes

- [x] Refactor
- [x] Feature

## Related issues

Resolve #1382

Related issues #914, #<issue>

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/982072/88bf7d19-b688-454e-869f-f858860c23c3

2023-08-23 13:51 UTC, LamaEats commented on src/components/GoalCriteria/GoalCriteria.tsx
> +            rawIcon={
why are you rename this prop? it's icon for table row not raw :)

2023-08-23 13:51 UTC, LamaEats commented on src/components/GoalListItemCompact.tsx
> +                    {rawIcon || <IconTargetOutline size="s" />}
can pass `<IconTargetOutline size="s" />` as default value for `rawIcon` prop

2023-08-23 22:20 UTC, awinogradov commented
ping @9teen90nine

2023-08-24 07:24 UTC, 9teen90nine approved these changes

2023-08-24 09:09 UTC, LamaEats requested changes

2023-08-24 09:09 UTC, LamaEats commented on src/components/ListView.tsx
> +    const registerItem = useCallback((value: unknown) => items.push(value) - 1, [items]);
why you are changing memoized variable instead of `useState` returned value through setter function?

2023-08-24 09:22 UTC, LamaEats commented on src/components/ListView.tsx
> +    const registerItem = useCallback((value: unknown) => items.push(value) - 1, [items]);
or use returned value from `useRef` function

2023-08-24 09:36 UTC, LamaEats commented on src/components/ListView.tsx
> +    const registerItem = useCallback((value: unknown) => items.push(value) - 1, [items]);
also this code is not safety for multiple re-renders of the `ListViewItem` component

2023-08-26 16:07 UTC, merged