User can create goal criteria everywhere
taskany-inc/issues pull request #1623
Opened 2023-09-04 13:33 UTC by DenisVorop

## PR includes
- [x] Bug Fix

## Related issues
Resolve #1485 

## QA Instructions, Screenshots, Recordings
  
<img width="684" alt="Снимок экрана 2023-09-04 в 16 24 31" src="https://github.com/taskany-inc/issues/assets/95316053/17460d32-6026-4634-8402-f8e03386db6a">

2023-09-04 16:34 UTC, awinogradov requested changes
PR doesn't follow guidelines

2023-09-05 09:33 UTC, 9teen90nine approved these changes

2023-09-05 16:19 UTC, awinogradov requested changes

2023-09-05 16:19 UTC, awinogradov commented on src/components/GoalCriteria/GoalCriteria.tsx
> +    canCreate: boolean;
Component must be refactored. It's better to use composition instead. U can pass or not smth to render via props instead of using props as condition

2023-09-06 12:18 UTC, awinogradov requested changes

2023-09-06 12:18 UTC, awinogradov commented on src/components/GoalPage/GoalPage.tsx
> +                                                _isEditable && (
nullable

2023-09-06 15:27 UTC, awinogradov approved these changes

2023-09-06 15:45 UTC, merged