feat(Estimates): Date Ranges
taskany-inc/issues pull request #1628
Opened 2023-09-06 08:54 UTC by sab94a

## PR includes

- [x] Refactor
- [x] Feature

## Related issues

Resolve #1627

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/9020793/022aa8fc-9f7b-48a1-b8ee-1efaaf14eaf8

2023-09-09 15:08 UTC, sab94a commented
Uploading Запись экрана 2023-09-09 в 17.58.56.mov…

2023-09-09 15:10 UTC, sab94a commented
https://github.com/taskany-inc/issues/assets/9020793/f0830c60-93aa-41c0-9657-1e4091ad32fd

2023-09-12 10:02 UTC, sab94a commented
Before Migration

![telegram-cloud-photo-size-2-5188671830938995917-y](https://github.com/taskany-inc/issues/assets/9020793/05423de8-2f11-4ab8-872f-68f17bec286c)
![telegram-cloud-photo-size-2-5188671830938995919-y](https://github.com/taskany-inc/issues/assets/9020793/889f7aac-c306-4bab-9cac-f85dcb1c3727)
![telegram-cloud-photo-size-2-5188671830938995920-y](https://github.com/taskany-inc/issues/assets/9020793/350b77db-e006-4b59-9f86-a8040179b3e3)

2023-09-12 10:03 UTC, sab94a commented
Successful Migration!

`npx prisma migrate dev`
`npm run db:migrate:estimates`

https://github.com/taskany-inc/issues/assets/9020793/de49fea0-c5f8-4680-92f5-c4ff12e27263

2023-09-12 14:27 UTC, sab94a commented
Redirects from legacy estimate filter: 

https://github.com/taskany-inc/issues/assets/9020793/f3d0bd2b-85bf-4ffc-9386-c37f2a8dea54

2023-09-13 23:22 UTC, awinogradov requested changes

2023-09-13 23:22 UTC, awinogradov commented on package.json
> +    "db:migrate:estimates": "ts-node -r dotenv/config scripts/estimatesMigrate.ts",
What?

2023-09-13 23:22 UTC, awinogradov commented on prisma/schema.prisma
> +  legacyEstimate          EstimateToGoal[]
I think it must be vise versa. We don't need to rename current fields. Add new only.

2023-09-13 23:22 UTC, awinogradov commented on scripts/estimatesMigrate.ts
> +// TODO: Remove script here https://github.com/taskany-inc/issues/issues/1656
It doesn't help to understand what is this and why

2023-09-13 23:22 UTC, awinogradov commented on src/components/GoalDependencyList/GoalDependencyList.tsx
> +import { State, DateType } from '@prisma/client';
Sorry, we have issue about clean up such as imports

2023-09-13 23:22 UTC, awinogradov commented on src/components/GoalEditForm/GoalEditForm.tsx
> +    const { estimate, estimateType } = goal;
It helps really?

2023-09-19 08:23 UTC, awinogradov approved these changes

2023-09-20 19:12 UTC, asabotovich commented
resolve #1669

2023-09-21 14:48 UTC, merged