Use PageTitlePreset on all pages
taskany-inc/issues pull request #1653
Opened 2023-09-11 13:26 UTC by DenisVorop

## PR includes
- [x] Refactor

## Related issues
Resolve #1603

2023-09-11 13:28 UTC, 9teen90nine commented
what about project page?

2023-09-13 08:47 UTC, 9teen90nine commented on src/components/ProjectsPage/ProjectsPage.tsx
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
we don't do that

2023-09-13 08:47 UTC, 9teen90nine commented on src/hooks/useProjectResource.ts
> +            if (!id) return;
maybe you should create a guard function to avoid this copypaste?

2023-09-20 19:10 UTC, awinogradov requested changes
If we have `ProjectsPage` only do we really need `ProjectPageLayout`?

2023-09-21 09:21 UTC, 9teen90nine approved these changes

2023-09-21 10:45 UTC, merged