E2E: Project /
taskany-inc/issues pull request #1681
Opened 2023-09-20 15:16 UTC by LamaEats

Written a new test specs for project page, ex. page have correct data by specific key, empty project have inline control for create first goal into specific project

Also add a new npm command for local run tests outside of Docker

## PR includes

- [x] Bug Fix
- [x] Specs
- [x] Refactor
- [x] DX

## Related issues

Resolve #1640

2023-09-21 11:41 UTC, awinogradov requested changes

2023-09-21 11:41 UTC, awinogradov commented on src/components/InlineCreateGoalControl/InlineCreateGoalControl.tsx
> +    nullable(visible, () => (
Must be in place of component usage

2023-09-21 11:41 UTC, awinogradov commented on src/components/ProjectPageLayout/ProjectPageLayout.tsx
Component doesn't exists in main branch

2023-09-22 12:18 UTC, awinogradov approved these changes

2023-09-22 12:22 UTC, 9teen90nine approved these changes

2023-09-25 11:34 UTC, merged