Align text in GoalListItem
taskany-inc/issues pull request #1706
Opened 2023-09-25 15:51 UTC by Troff8

## PR includes

- [ ] Bug Fix

## Related issues

Resolve [#1695 ](https://github.com/taskany-inc/issues/issues/1695)

## QA Instructions, Screenshots, Recordings
  
<img width="905" alt="Снимок экрана 2023-09-25 в 18 49 13" src="https://github.com/taskany-inc/issues/assets/87986652/dc857536-f8ad-4d12-97eb-9010aaf0104d">

2023-09-26 08:58 UTC, awinogradov approved these changes

2023-09-26 12:04 UTC, 9teen90nine approved these changes

2023-09-26 19:35 UTC, awinogradov requested changes

2023-09-26 19:35 UTC, awinogradov commented on src/components/GoalListItem.tsx
> +                                    <CommentsCountIcon size="s" />
No way! I asked about smth vice versa...

2023-09-27 21:08 UTC, awinogradov approved these changes

2023-09-28 07:37 UTC, merged