e2e test for possibility to edit goals and comments
taskany-inc/issues pull request #1717
Opened 2023-09-27 08:40 UTC by asabotovich

## PR includes

- [x] Specs

## Related issues

Resolve #1707 

## QA Instructions, Screenshots, Recordings

2023-10-11 10:20 UTC, awinogradov requested changes

2023-10-11 10:20 UTC, awinogradov commented on src/components/GoalPage/GoalPage.tsx
> +                                        {...issueEditButton.attr}
goalEditButton

2023-10-11 10:20 UTC, awinogradov commented on src/components/GoalSidebar/GoalSidebar.tsx
> +                            {...issueDeleteButton.attr}
goalDeleteButton

2023-10-11 10:20 UTC, awinogradov commented on src/utils/domObjects.ts
> +export const issueEditButton = issuePage.add('edit');
lets rename all of them with `goal*`. Thanks!

2023-10-11 10:20 UTC, awinogradov commented on cypress/plugins/db.ts
> +            await prisma.goalHistory.deleteMany({
I'm not sure is ok. It must works with cascade

2023-10-11 10:20 UTC, awinogradov commented on cypress/support/index.ts
> +        cy.get(goalActionCreateOnly.query).should('exist').and('be.visible').click();
What plan u have to check other ways?

2023-10-11 10:20 UTC, awinogradov commented on cypress/support/index.ts
> +type CreateGoalFields = {
Copy/paste

2023-10-12 19:18 UTC, awinogradov commented on prisma/schema.prisma
> +  goalAsCriteria   Goal?    @relation("GoalAsCriteria", fields: [goalIdAsCriteria], references: [id], onDelete: Cascade)
think twice

2023-10-13 11:46 UTC, awinogradov approved these changes

2023-10-13 12:05 UTC, 9teen90nine approved these changes

2023-10-13 13:12 UTC, merged