Move Estimate filter into Filters tabs popup
taskany-inc/issues pull request #1724
Opened 2023-09-27 17:06 UTC by asabotovich

## PR includes

- [x] Feature

## Related issues

Resolve #1696 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/issues/assets/9020793/3359b7ed-af61-460a-881a-3af7fdd5c059

2023-09-27 21:20 UTC, awinogradov requested changes

2023-09-27 21:20 UTC, awinogradov commented on src/components/Estimate/Estimate.tsx
> +    width: 12px;
Sorry, but it's impossible to use custom sizes for icons... U must use @taskany/icons instead. Thanks for understanding.

2023-09-27 21:40 UTC, LamaEats commented on src/components/Estimate/Estimate.tsx
> +export const getReadOnlyFileds = (type: EstimateValue['type']) => {
Fileds -> Fields

2023-09-28 11:44 UTC, LamaEats approved these changes

2023-09-28 11:44 UTC, LamaEats commented on src/components/Estimate/Estimate.tsx
> +                clue={`${tr('Quarter clue')} ${getQuarterFromDate(new Date())}.`}
why is not translated template string formatted through `tr.raw` function?

2023-09-28 13:19 UTC, asabotovich commented
Fix text size and humanize translations
<img width="1431" alt="Screenshot 2023-09-28 at 16 03 12" src="https://github.com/taskany-inc/issues/assets/9020793/9504f8bf-9c7d-45d2-a63a-d876bbc63aec">

2023-09-28 14:23 UTC, asabotovich commented
Design fixes

<img width="741" alt="Screenshot 2023-09-28 at 17 22 59" src="https://github.com/taskany-inc/issues/assets/9020793/af22173e-dc43-4236-a4a1-3ae57c2c6261">

2023-09-28 15:07 UTC, awinogradov approved these changes

2023-09-28 15:11 UTC, asabotovich commented
Resovle: #1734

2023-09-28 15:18 UTC, merged