Drop /goals page
taskany-inc/issues pull request #1820
Opened 2023-10-10 08:11 UTC by LamaEats

## PR includes

- [ ] Bug Fix
- [ ] Docs
- [ ] Specs
- [x] Refactor
- [x] Feature
- [ ] DX
- [ ] DevOps

## Related issues

Resolve #1641 

## QA Instructions, Screenshots, Recordings

2023-10-12 19:58 UTC, awinogradov requested changes
<img width="782" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/3a8c789e-257e-4618-8585-1bc297052b8c">

In ru `Сгруппировать/Разгруппировать`

2023-10-13 12:31 UTC, 9teen90nine approved these changes

2023-10-13 13:57 UTC, LamaEats commented
<img width="897" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/bb227d98-ed57-4327-874c-cfbad4c9deee">

2023-10-13 14:29 UTC, LamaEats commented
<img width="897" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/015c3712-60e3-4ade-9d60-31754eb63a0b">

2023-10-13 15:15 UTC, awinogradov approved these changes

2023-10-13 15:22 UTC, merged