Issues/2000
taskany-inc/issues pull request #2001
Opened 2023-11-08 11:32 UTC by LamaEats

## PR includes

- [ ] Bug Fix
- [ ] Docs
- [ ] Specs
- [ ] Refactor
- [ ] Feature
- [ ] DX
- [ ] DevOps

## Related issues

Resolve #<issue>

Related issues #<issue>, #<issue>

## QA Instructions, Screenshots, Recordings
  
_Please replace this line with instructions on how to test your changes, a note on the devices and browsers this has been tested on, as well as any relevant images for UI changes._

2023-11-15 22:56 UTC, awinogradov requested changes

2023-11-15 22:56 UTC, awinogradov commented on src/components/GoalCriteria/GoalCriteria.tsx
> +                    shortId: `${item.criteriaGoal.projectId}-${item.criteriaGoal.scopeId}`,
Must be on server-side

2023-11-15 22:56 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.tsx
> +                    _shortId: `${criteriaGoal.projectId}-${criteriaGoal.scopeId}`,
Must be on server-side

2023-11-15 22:56 UTC, awinogradov commented on src/utils/db.ts
> +    const groupedCriteriaListByGoals = criteriaList.reduce<{ [key: string]: CriteriaItem[] }>((acc, criteria) => {
`Record<string, CriteriaItem[]>`

2023-11-15 22:56 UTC, awinogradov commented on trpc/queries/goals.ts
> +    console.log(list);
;)

2023-11-20 09:16 UTC, LamaEats commented on src/components/GoalCriteria/GoalCriteria.tsx
> +                    shortId: `${item.criteriaGoal.projectId}-${item.criteriaGoal.scopeId}`,
Will fix in #1997

2023-11-20 09:23 UTC, LamaEats commented on src/components/HistoryRecord/HistoryRecord.tsx
> +                    _shortId: `${criteriaGoal.projectId}-${criteriaGoal.scopeId}`,
will fix in in #2043

2023-11-21 08:45 UTC, tsumo approved these changes

2023-11-22 19:39 UTC, asabotovich commented on trpc/queries/goals.ts
> +                      }: GoalAchieveCriteria & { criteriaGoal: (Goal & { state: State | null }) | null }) => ({
Can we use the same structure in calcAchievedWeight and avoid map for every usage?

2023-11-23 09:12 UTC, closed without merging