Rotatable Tip
taskany-inc/issues pull request #2008
Opened 2023-11-09 12:36 UTC by DenisVorop

## PR includes
- [x] Feature

## Related issues
Resolve #1726 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/b7521ff3-3d73-48cd-9ce2-0ac5a3099363

2023-11-09 12:55 UTC, awinogradov requested changes

2023-11-09 12:55 UTC, awinogradov commented on src/components/RotatableTip/RotatableTip.tsx
> +    const contextTips: Record<TipContext, ((ctx?: TipContext) => ReactNode)[]> = {
Have u ever heard about memoization?:)

2023-11-09 12:55 UTC, awinogradov commented on src/components/RotatableTip/RotatableTip.tsx
> +            (ctx) => generateTip('Press {key} to create {entity}', { ctx }),
I think we can use `Press {key} to save {entity}` for both cases.

2023-11-09 13:36 UTC, awinogradov approved these changes

2023-11-09 20:09 UTC, awinogradov approved these changes

2023-11-10 09:33 UTC, 9teen90nine commented on src/components/RotatableTip/RotatableTip.tsx
> +            {allTips[Math.floor(Math.random() * allTips.length)](context)}
You probably should cache index into a useMemo

2023-11-10 09:33 UTC, 9teen90nine commented on src/components/RotatableTip/RotatableTip.tsx
> +export default RotatableTip;
default export?

2023-11-10 09:40 UTC, DenisVorop commented on src/components/RotatableTip/RotatableTip.tsx
> +export default RotatableTip;
that needed to use dynamic import

2023-11-10 09:45 UTC, 9teen90nine approved these changes

2023-11-10 10:21 UTC, merged