Sync new goal criteria & deps forms
taskany-inc/issues pull request #2045
Opened 2023-11-20 17:28 UTC by DenisVorop

## PR includes

- [x] Refactor

## Related issues

Resolve #1990 

## QA Instructions, Screenshots, Recordings

### Get error "uniq title"
  
https://github.com/taskany-inc/issues/assets/95316053/c6db6d78-0c12-4ebe-be98-bc5dbac443b7

###  Create criteria as non-goal

https://github.com/taskany-inc/issues/assets/95316053/3be2a121-e475-493d-b444-2d8633bc4ea8

### Show create criteria as goal

https://github.com/taskany-inc/issues/assets/95316053/c2e6a0ae-8a59-49e3-8114-9f3c645f24e1

###  Show max weight of criteria

https://github.com/taskany-inc/issues/assets/95316053/15176f4a-eb4a-4787-8ee2-46520b60ff01

### Show edit criteria

https://github.com/taskany-inc/issues/assets/95316053/ca00724f-4778-4ca3-a63c-951cea55fd99

### Show create versa criteria

https://github.com/taskany-inc/issues/assets/95316053/769ab92c-9fe2-4458-8464-14a31a6c32ea

2023-11-28 12:35 UTC, tsumo commented
There's a bunch of conflicts with the main branch, let's fix them before the review

2023-11-29 10:15 UTC, LamaEats requested changes
Doesn't works with recalculate weights by editing criteria
Remove extra icon in input if simple mode add/edit criteria

2023-11-29 16:48 UTC, DenisVorop commented on src/components/CriteriaForm/CriteriaForm.tsx
> +                id: z.string(),
<img width="536" alt="Снимок экрана 2023-11-29 в 19 47 08" src="https://github.com/taskany-inc/issues/assets/95316053/84cd08bf-1b66-4e1e-b7a9-f8d4aeba86bf">
<img width="513" alt="Снимок экрана 2023-11-29 в 19 47 12" src="https://github.com/taskany-inc/issues/assets/95316053/506ae2aa-0f8d-4f81-9550-ef8425e4524e">
<img width="493" alt="Снимок экрана 2023-11-29 в 19 47 47" src="https://github.com/taskany-inc/issues/assets/95316053/475aa428-c960-46b4-8d67-07b839c85e63">

2023-12-04 15:48 UTC, asabotovich approved these changes

2023-12-04 17:46 UTC, merged