useCopyToClipboard from bricks
taskany-inc/issues pull request #2226
Opened 2024-01-24 09:00 UTC by Katrin-kudryash

## PR includes

- [ ] Feature

## Related issues

Resolve #2216

2024-01-24 09:14 UTC, 9teen90nine requested changes

2024-01-24 09:14 UTC, 9teen90nine commented on src/components/GoalContentHeader/GoalContentHeader.tsx
the hook from bricks accepts onError

2024-01-24 13:02 UTC, tsumo approved these changes

2024-01-25 09:15 UTC, 9teen90nine approved these changes

2024-01-25 09:16 UTC, asabotovich approved these changes

2024-01-25 09:36 UTC, merged