Remove prisma deps from worker
taskany-inc/issues pull request #2250
Opened 2024-02-01 15:44 UTC by nyet-ty

Resolve #2227 

## PR includes

- [x] Refactor

2024-02-01 16:45 UTC, awinogradov requested changes
<img width="483" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/5e6fcd80-77c5-44c8-a441-01fb31ed8280">

2024-02-06 14:22 UTC, LamaEats requested changes

2024-02-06 14:22 UTC, LamaEats commented on src/utils/worker/index.ts
> +const onQueeTooLong = () => Sentry.captureMessage('Queue too long. Smth went wrong.');
`onQueeTooLong` => `onQueueTooLong`

2024-02-06 14:22 UTC, LamaEats commented on src/utils/worker/index.ts
> +const onError = (error: any) => console.log(error.message);
Maybe `Sentry.captureException` instead of `console.log`

2024-02-06 14:22 UTC, LamaEats commented on tsconfig.json
> +            "module": "node16",
why not node@20?

2024-03-25 13:05 UTC, closed without merging