Issues/2215
taskany-inc/issues pull request #2328
Opened 2024-02-15 17:45 UTC by asabotovich

## PR includes

- [x] Feature

## Related issues

Resolve #2215 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/9020793/11251450-ad83-439c-8298-040392020b52

2024-02-16 12:57 UTC, asabotovich commented
<img width="1075" alt="Screenshot 2024-02-16 at 15 54 33" src="https://github.com/taskany-inc/issues/assets/9020793/efada712-55af-4da2-8f2a-3759de639bab">

2024-02-16 15:02 UTC, tsumo commented on src/components/ProjectTeamPage/ProjectTeamPage.tsx
> +    console.log('QQQ TEAMS', teams);
:)

2024-02-19 11:28 UTC, asabotovich commented
https://github.com/taskany-inc/issues/assets/9020793/6c020c2a-f48b-46be-82d7-20be31c6c1c3

2024-02-19 13:20 UTC, LamaEats commented on src/components/TeamComboBox.tsx
> +            <ComboBox
Why legacy component instead of Dropdown and AutoComplete from `harmony`?

2024-02-19 13:20 UTC, LamaEats commented on prisma/schema.prisma
> +  teams        String[]
maybe call as `externalTeams`? Because get it from other service

2024-02-19 13:20 UTC, LamaEats commented on src/types/crew.ts
> +interface Membership {
define before usage

2024-02-19 14:17 UTC, awinogradov requested changes

2024-02-19 14:17 UTC, awinogradov commented on src/components/ProjectTeamPage/ProjectTeamPage.tsx
> +import { nullable, TreeView, TreeViewElement, TreeViewNode } from '@taskany/bricks';
harmony/TreeView

2024-02-21 09:50 UTC, asabotovich commented on src/components/TeamComboBox.tsx
> +import { ComboBox } from '@taskany/bricks';
fixed

2024-02-21 09:50 UTC, asabotovich commented on src/components/TeamListItem.tsx
> +import { TableCell } from '@taskany/bricks';
will be fixed here https://github.com/taskany-inc/issues/issues/2266

2024-02-21 09:50 UTC, asabotovich commented on src/types/crew.ts
> +interface Membership {
fixed

2024-02-21 09:51 UTC, asabotovich commented
![telegram-cloud-photo-size-2-5379648148756091773-y](https://github.com/taskany-inc/issues/assets/9020793/aaacddf9-0242-43a6-8973-ace1c343fe91)

2024-02-21 10:59 UTC, tsumo approved these changes

2024-02-21 16:25 UTC, merged