Remove Table from bricks usage
taskany-inc/issues pull request #2368
Opened 2024-02-22 18:12 UTC by asabotovich

## PR includes

- [x] Refactor

## Related issues

Resolve #2266 

## QA Instructions, Screenshots, Recordings

2024-02-27 15:57 UTC, awinogradov requested changes

2024-02-27 15:57 UTC, awinogradov commented on src/components/GlobalSearch/GlobalSearch.module.css
> +.GlobalSeachTable {
Sea`R`ch

2024-02-27 15:57 UTC, awinogradov commented on src/components/GlobalSearch/GlobalSearch.tsx
> +                                                                    { name: 'title', columnProps: { width: '32%' } },
32? Why not 32.7?

2024-02-27 15:57 UTC, awinogradov commented on src/components/GoalCriteria/GoalCriteria.module.css
> +.GoalCriteriaCheckBox_checked, .GoalCriteriaCheckBox_checked:hover{
Add space before bracket
Also would be better to write list of selectors on column, not in a row

2024-02-28 10:48 UTC, tsumo approved these changes

2024-02-28 11:18 UTC, awinogradov approved these changes

2024-02-28 11:21 UTC, merged