Applied filters bar
taskany-inc/issues pull request #2417
Opened 2024-03-05 18:24 UTC by DenisVorop

Pt. 1. Only readOnly view

## PR includes

- [x] Refactor

## Related issues

Resolve #2350 

## QA Instructions, Screenshots, Recordings

https://github.com/taskany-inc/issues/assets/95316053/7064e94f-7e17-4f9e-825c-a92f4768711b

2024-03-11 09:43 UTC, awinogradov requested changes
<img width="299" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/5dd9c76d-997f-4b20-b0c5-d99ba9ef969b">

I don't see hovers on dropdown value

2024-03-11 17:24 UTC, DenisVorop commented
<img width="1440" alt="Снимок экрана 2024-03-11 в 19 49 44" src="https://github.com/taskany-inc/issues/assets/95316053/6399d63b-e3f2-48e9-8024-e50a8a29a266">

2024-03-20 15:02 UTC, awinogradov requested changes

2024-03-20 16:17 UTC, asabotovich approved these changes

2024-03-20 17:09 UTC, merged