Do not override bricks via SC. PART 2
taskany-inc/issues pull request #2474
Opened 2024-03-19 20:47 UTC by DenisVorop

## PR includes

- [x] Refactor

## Related issues

Resolve #2473

2024-03-26 13:15 UTC, awinogradov requested changes

2024-03-26 13:15 UTC, awinogradov commented on src/components/Badge/Badge.module.css
https://taskany-inc.github.io/bricks/?path=/story/harmony-badge--default

2024-03-26 13:15 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.module.css
> +.Badge {
Looks like the new one?

2024-03-26 13:15 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.module.css
> +.FlexReset {
?

2024-03-26 13:15 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.module.css
> +        icon by center of first line in content
@LamaEats added align for icons. Why this no-magic is here?

2024-03-26 13:15 UTC, awinogradov commented on src/components/HistoryRecord/HistoryRecord.module.css
> +.HistoryRecordWrapper {
We have new HistoryRecord. Do we really need to add so many overrides. https://taskany-inc.github.io/bricks/?path=/story/harmony-historyrecord--default

2024-03-26 13:15 UTC, awinogradov commented on src/components/InlineTrigger/InlineTrigger.module.css
> +.InlineTrigger {
Looks like Badge component

2024-03-27 19:21 UTC, tsumo reviewed
Conflicts with main brach

2024-04-01 09:09 UTC, DenisVorop commented
blocked by https://github.com/taskany-inc/issues/issues/2416

2024-04-11 09:14 UTC, 9teen90nine approved these changes

2024-04-11 11:55 UTC, tsumo approved these changes

2024-04-12 09:19 UTC, merged