Do not override bricks via SC. PART 1
taskany-inc/issues pull request #2475
Opened 2024-03-19 20:50 UTC by DenisVorop

## PR includes

- [x] Refactor

## Related issues

Resolve #2472

2024-03-26 13:03 UTC, awinogradov requested changes

2024-03-26 13:03 UTC, awinogradov commented on src/components/ScrollableView/ScrollableView.tsx
> +                key={`left-${shades.left}`}
Do u really need this key?

2024-03-27 18:06 UTC, awinogradov commented on src/components/ImageFullScreen/ImageFullScreen.module.css
> +    cursor: pointer;
Vice versa ;)

2024-03-27 19:20 UTC, tsumo approved these changes

2024-03-27 19:43 UTC, awinogradov approved these changes

2024-03-27 19:58 UTC, merged