Navigation Sidebar: add Presets section
taskany-inc/issues pull request #2487
Opened 2024-03-21 17:49 UTC by asabotovich

## PR includes

- [x] Feature

## Related issues

Resolve #2462 

Related issues #2349 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/9020793/62443ae0-df0b-4eab-9436-d19766221d4a

2024-03-25 14:35 UTC, DenisVorop commented on src/components/PageNavigation/PageNavigation.tsx
> +            isPresetActive: presetRoutes.find((item) => item.href === nextRouter.asPath),
maybe it would be better to cast to boolean type

2024-03-26 13:09 UTC, LamaEats requested changes

2024-03-26 13:09 UTC, LamaEats commented on src/components/PageNavigation/PageNavigation.tsx
> +            isPresetActive: Boolean(presetRoutes.find((item) => item.href === nextRouter.asPath)),
Replace  `Boolean([].find)` by `[].some`

2024-03-26 21:20 UTC, asabotovich commented on src/components/PageNavigation/PageNavigation.tsx
> +            isPresetActive: Boolean(presetRoutes.find((item) => item.href === nextRouter.asPath)),
Exactly!

2024-03-27 15:03 UTC, LamaEats approved these changes

2024-03-27 15:04 UTC, merged