feat(emails): new components for emails
taskany-inc/issues pull request #2489
Opened 2024-03-22 14:50 UTC by LamaEats

Component for email templates based on React Emails lib

## PR includes

- [x] Feature

## Related issues

Resolve #2330 

## QA Instructions, Screenshots, Recordings
  
<img width="750" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/15b52963-1395-4cca-8243-3c41a1ad6ba5">

2024-03-25 12:22 UTC, awinogradov requested changes
<img width="424" alt="image" src="https://github.com/taskany-inc/issues/assets/982072/74a15157-d6e8-4e59-8ce6-ea6cc5b9ce5b">

2024-03-26 13:19 UTC, awinogradov commented on emails/_components/Tooltip.tsx
> +    view: 'success' | 'warning';
`keyof typeof colors`

2024-03-26 13:22 UTC, awinogradov approved these changes
Some comments for the code beauty ❤️

2024-03-26 21:25 UTC, asabotovich approved these changes

2024-03-27 08:26 UTC, merged