Applied filters bar interactive
taskany-inc/issues pull request #2490
Opened 2024-03-22 17:16 UTC by DenisVorop

## PR includes

- [x] Feature

## Related issues

Resolve #2481 

## QA Instructions, Screenshots, Recordings
  

https://github.com/taskany-inc/issues/assets/95316053/85aee7d4-ec7d-4132-ae46-8e20275eb877

https://github.com/taskany-inc/issues/assets/95316053/0b2b21ac-b029-404f-aa01-9c71e166ce96

2024-03-26 13:14 UTC, LamaEats requested changes

2024-03-26 13:14 UTC, LamaEats commented on src/components/AppliedStateFilter/AppliedStateFilter.tsx
> +import { StateType } from '@prisma/client';
don't make more warnings

2024-03-27 15:04 UTC, LamaEats approved these changes

2024-03-27 22:57 UTC, asabotovich requested changes

2024-03-27 22:57 UTC, asabotovich commented on src/components/AppliedStateFilter/AppliedStateFilter.tsx
> +            if (stateTypesRef.current?.length) {
why do we need this check?

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
> +            batchQueryState?.({ ...filterQueryRef.current });
we have queueMicrotask inside `batchQueryState`

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
usually we use ref to exclude value from deps...

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
> +                            isFiltersEmpty && !groupedByProject,
new business logic? Are we really going to disable ability to apply filters for grouped view?

2024-03-27 22:57 UTC, asabotovich commented on src/components/AppliedStateFilter/AppliedStateFilter.tsx
> +        onStateTypeChange?.();
is in different from ` onStateTypeChange?.(undefined);` several lines above

2024-03-27 22:57 UTC, asabotovich commented on src/components/AppliedStateFilter/AppliedStateFilter.tsx
> +    onStateTypeChange,
we don't need additional prop `onStateTypeChange`, If we just reset `stateType` on `state` change

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
> +    const filterQueryRef = useLatest(filterQuery);
also, we don't need this

2024-03-27 22:57 UTC, asabotovich commented on src/hooks/useUrlFilterParams.ts
> +export type SortableProps =
unused export

2024-03-27 22:57 UTC, asabotovich commented on src/utils/dateTime.ts
> +    if (!value) {
unnecessary check (exist inside `decodeUrlDateRange`)

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersBar/FiltersBar.tsx
> +    setPartialQueryByKey: <K extends keyof QueryState>(key: K) => (value?: QueryState[K] | undefined) => void;
it's a part of Filters panel internal logic!

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersBar/FiltersBar.tsx
> +    }, [filterQuery, filterItems]);
You should pass final items from FiltersPanel

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersBar/FiltersBar.tsx
> +                onChange={({ id }) => setPartialQueryByKey(id as keyof QueryState)([])}
`<AddFilterDropdown />` shouldn't know anything about `queryState` or `<FiltersPanel />`

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
>      const setPartialQueryByKey = useCallback(<K extends keyof QueryState>(key: K) => {
Assume, we can remove this logic and push values directly to router by batchQueryState if we update state per every filter

2024-03-27 22:57 UTC, asabotovich commented on src/components/FiltersPanel/FiltersPanel.tsx
>      const [filterQuery, setFilterQuery] = useState<Partial<FilterQueryState> | undefined>(queryFilterState);
after that we can remove this additional state..

2024-04-03 09:12 UTC, 9teen90nine commented on src/components/AppliedGoalParentFilter/AppliedGoalParentFilter.tsx
> +    }, [onChange, onClose]);
you could probably wrap these two into a single hook and use once instead of copypaste

2024-04-03 20:54 UTC, 9teen90nine approved these changes

2024-04-03 20:57 UTC, asabotovich approved these changes

2024-04-03 21:16 UTC, merged