GoalCriteria: new design for criteria type Switch
taskany-inc/issues pull request #2612
Opened 2024-04-15 08:00 UTC by LamaEats

## PR includes

- [x] Feature

## Related issues

Resolve #2506 

## QA Instructions, Screenshots, Recordings
  
<img width="460" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/05a4f0cb-688f-4940-9925-740ea73675b6">
<img width="460" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/66648ec2-e44f-4c29-a0a2-fac654f4ecfa">
<img width="460" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/038f5557-b911-48bf-89c2-99686a128b9c">
<img width="460" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/a0c5a2e4-d1bf-4741-9c48-5f32666cbc6b">
<img width="460" alt="image" src="https://github.com/taskany-inc/issues/assets/7002692/649440ca-8e77-4a42-abb4-de3ff85b2ae1">

2024-04-15 09:41 UTC, 9teen90nine requested changes

2024-04-15 09:41 UTC, 9teen90nine commented on src/components/CriteriaForm/CriteriaForm.tsx
> +            if (target instanceof HTMLElement) {
there should be a way to set input value without dom search

2024-04-18 17:30 UTC, asabotovich commented on src/components/CriteriaForm/CriteriaForm.module.css
> +    width: 10ch;
Why we can't control input width without hacks?

2024-04-18 17:30 UTC, asabotovich commented on src/components/CriteriaForm/CriteriaForm.tsx
> +        (_: any, active: string) => {
`:React.SyntheticEvent<HTMLButtonElement>` 
<img width="673" alt="Screenshot 2024-04-18 at 20 28 19" src="https://github.com/taskany-inc/issues/assets/9020793/557aa6ea-930b-4c3c-8aeb-1ea491645d3a">

2024-04-23 10:02 UTC, tsumo approved these changes

2024-04-23 13:59 UTC, 9teen90nine approved these changes

2024-04-23 14:07 UTC, merged