Fix markdown
taskany-inc/issues pull request #2718
Opened 2024-05-29 14:01 UTC by asabotovich

## PR includes

- [x] Bug Fix

## Related issues

Resolve #2717 

## QA Instructions, Screenshots, Recordings
  
<img width="742" alt="Снимок экрана 2024-05-29 в 17 00 27" src="https://github.com/taskany-inc/issues/assets/9020793/76548a3c-7ab8-44a9-a0bf-ce2eb9b52ec6">

2024-05-29 14:17 UTC, LamaEats requested changes

2024-05-29 14:17 UTC, LamaEats commented on src/components/WhatsNewLayout.tsx
> +    a: (props: AnchorHTMLAttributes<HTMLAnchorElement>) => <Link {...props} target="_blank" view="inline" />,
Could you use single components list for both components (whatsnew/md) with in-place overrides?

2024-05-29 14:21 UTC, DenisVorop commented on package.json
> +    "@taskany/bricks": "0.0.0-ef96135",
be careful

2024-05-29 19:48 UTC, LamaEats approved these changes

2024-05-30 08:30 UTC, tsumo approved these changes

2024-05-30 08:56 UTC, merged