Add starred projects tab
taskany-inc/issues pull request #2805
Opened 2024-07-15 16:39 UTC by IgorGoryany

## PR includes

- [x] Feature

## Related issues

Resolve #2798

2024-07-16 13:32 UTC, tsumo approved these changes

2024-07-16 15:48 UTC, LamaEats requested changes

2024-07-16 15:48 UTC, LamaEats commented on trpc/router/project.ts
> +        return prisma.project
Please, rewrite this query with kysely instead of prisma. If you have any questions about of sql and kysely then you can ask me

2024-07-18 15:47 UTC, LamaEats approved these changes

2024-07-19 09:02 UTC, asabotovich approved these changes

2024-07-19 09:24 UTC, merged