Add plus icon to project row on dashboard
taskany-inc/issues pull request #2876
Opened 2024-08-07 11:59 UTC by IgorGoryany

## PR includes

- [x] Feature

## Related issues

Resolve #2866

## QA Instructions, Screenshots, Recordings

2024-08-07 13:09 UTC, tsumo commented
Tests are failing

2024-08-09 08:34 UTC, tsumo requested changes

2024-08-09 08:34 UTC, tsumo commented on src/components/StarButton/StarButton.tsx
> +export const Icon: React.FC<IconProps> = ({ filled }) => {
StarButtonBase would be a better name for exported component

2024-08-09 08:34 UTC, tsumo commented on src/components/ProjectSubscriptionIconButtons/ProjectSubscriptionIconButtons.tsx
> +            <button className={s.ProjectSubscriptionIconButtons} onClick={onWatchClick} {...watch.attr}>
Why not harmony buttons?

2024-08-12 15:04 UTC, asabotovich requested changes

2024-08-12 15:04 UTC, asabotovich commented on src/components/ProjectListItem/ProjectListItem.tsx
>                          ))}
I think we don't need this anymore

It should be `<ProjectSubscriptionButtons view='icons'  editable={false} />`

2024-08-12 16:02 UTC, tsumo approved these changes

2024-08-12 16:21 UTC, merged