CriteriaForm doesn't know the current criteria list by change them
taskany-inc/issues pull request #2893
Opened 2024-08-13 12:45 UTC by LamaEats

## PR includes

- [x] Bug Fix

## Related issues

Resolve #2880

2024-08-14 19:50 UTC, asabotovich requested changes

2024-08-14 19:50 UTC, asabotovich commented on src/components/GoalCriteriaSuggest.tsx
> +
can we keep it in helper?

2024-08-14 19:50 UTC, asabotovich commented on src/hooks/useGoalResource.ts
> +            debugger;
😱

2024-08-14 19:51 UTC, LamaEats commented on src/hooks/useGoalResource.ts
> +            debugger;
Oh sh

2024-08-15 09:58 UTC, LamaEats commented on src/components/GoalCriteriaSuggest.tsx
> +
make as a hook

2024-08-15 12:14 UTC, asabotovich approved these changes

2024-08-16 12:48 UTC, 9teen90nine approved these changes

2024-08-16 12:49 UTC, merged