Kanban: goals lazy pagination
taskany-inc/issues pull request #2959
Opened 2024-09-06 08:59 UTC by asabotovich

## PR includes

- [x] Feature

## Related issues

Resolve #2913

## QA Instructions, Screenshots, Recordings

2024-09-11 07:51 UTC, LamaEats requested changes

2024-09-11 07:51 UTC, LamaEats commented on src/components/Kanban/Kanban.tsx
> +const calculateCommonLoadingState = (map: Map<unknown, LoadingState>): LoadingState => {
Why is it so difficult? Could you're move state calculations logic on column level? Cause that level has fetching the data

2024-09-12 10:13 UTC, asabotovich commented on src/utils/projectCollapsableItemInit.ts
> +export const projectCollapsableItemInit = async <T extends { id: string; partnerProjectIds?: string[] }>({
it used on server side

2024-09-12 10:53 UTC, tsumo approved these changes

2024-09-12 13:58 UTC, 9teen90nine commented on src/components/Kanban/Kanban.tsx
> +    if (loadingStates.size === 1 && loadingStates.has('loaded')) {
![image](https://github.com/user-attachments/assets/72f07876-709f-4775-8cfc-457f908642e8)

2024-09-12 14:00 UTC, 9teen90nine approved these changes

2024-09-12 14:15 UTC, asabotovich commented on src/components/Kanban/Kanban.tsx
> +                        onLoadingStateChange={(loadingState) =>
it has current item deps

2024-09-12 15:00 UTC, merged