User filter access
taskany-inc/issues pull request #3066
Opened 2024-10-23 09:53 UTC by IgorGoryany

## PR includes

- [x] Feature

2024-10-24 05:42 UTC, LamaEats requested changes

2024-10-24 05:42 UTC, LamaEats commented on trpc/queries/filter.ts
> +        .$if(activityId.length > 0 && !isDefault && !id.length, (qb) =>
Different condition statements for a same comparisons

2024-10-24 05:42 UTC, LamaEats commented on trpc/queries/filter.ts
> +                            .$if(activityId.length > 0, (qb) => qb.where('_filterStargizers.A', '=', activityId)),
You were checked this variable early

2024-10-25 09:28 UTC, asabotovich approved these changes

2024-10-25 09:31 UTC, LamaEats approved these changes

2024-10-25 09:31 UTC, merged