FormInput width for the long text and absolute key control
taskany-inc/issues pull request #410
Opened 2022-11-28 15:56 UTC by BogdanFV

Resolve #173

2022-11-28 19:54 UTC, awinogradov requested changes

2022-11-28 19:54 UTC, awinogradov commented on src/components/CommonHeader.tsx
> +                <StyledCommonHeaderTitle size="xxl" weight="bolder" title={String(title)}>
А зачем здесь приведение типа? Ведь если там будет не строка, то будет что-то странное.

2022-11-28 19:54 UTC, awinogradov commented on src/components/FormInput.tsx
> +        background-color: var(--gray2);
На 44 строке явно не так используются константы, почему здесь так?

2022-11-28 19:54 UTC, awinogradov commented on src/utils/keyPredictor.ts
> +        .slice(0, 10);
Здесь бы коммент дописать почему так и зачем

2022-11-29 08:27 UTC, BogdanFV commented on src/components/CommonHeader.tsx
> +                <StyledCommonHeaderTitle size="xxl" weight="bolder" title={String(title)}>
Type 'null' is not assignable to type 'string | undefined'.

2022-11-29 08:55 UTC, awinogradov commented on src/components/CommonHeader.tsx
> +                <StyledCommonHeaderTitle size="xxl" weight="bolder" title={String(title)}>
<img width="138" alt="image" src="https://user-images.githubusercontent.com/982072/204483621-cb4e670c-c564-4572-8297-d107ec19112c.png">

2022-12-01 16:00 UTC, awinogradov approved these changes

2022-12-01 18:17 UTC, merged